### ISSUE TITLE
MVP Release Checklist

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/nijobs-be#153]
This issue aims to track the steps required in order to release NIJobs.

- [x] Set up env file for master (prod) on NIServer
- [x] Remove example route (example.js)
- [x] Create new MongoDB Atlas project for Production
- [x] Onboard at least 3 companies (ideally 5)
- [x] Review Constants/Rules (e.g. max 10 contacts per company is too much)
- [x] Add Job Fields/Techs (Backend + Frontend repos)
- [x] Test Behavior Flows (Create applications, review, approve, create offers, search, etc)
- [x] Review UI/UX (especially mobile) - Anything that might seem off in terms of spacing, colors etc
- [x] Social Media presence prep
- [x] Add rules
- [x] Create account for analytics and put the correct `ANALYTICS_ID` into the envfile
  - [x] It would be nice to have an account of only staging metrics, so that we can test new metrics before prod (just a matter of having a different account and putting a different `ANALYTICS_ID` in the staging .env file)
